#!/bin/ash
#
# Copyright (c) 2012 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

next_pack_to_install()
{
    next_pack "install"
}

next_pack_to_commit()
{
    next_pack "commit"
}

next_pack()
{
    local ACTION="$1"

    local FILE VAR PACK

    for PACK in $(ls -1d ${EXTRA_DATA_SEQUENCE}/* 2>/dev/null | sort -n) ; do
        case "${ACTION}" in
            install)
                FILE="${PACK}/installed.conf"
                VAR="INSTALLED"
                ;;
            commit)
                FILE="${PACK}/committed.conf"
                VAR="COMMITTED"
                ;;
            *)
                echo "ERROR: Unknown action '${ACTION}'" >&2
                return 1
        esac

        if [ -e "${FILE}" ] ; then
            . "${FILE}"
            if [ "$(get_var ${VAR})" -ne 1 ] ; then
                echo "${PACK}"
                return 0
            fi
        else
            echo "${PACK}"
            return 0
        fi
    done
    return 1
}

are_more_packs_pending_install()
{
    next_pack "install" >/dev/null
}

are_more_packs_pending_commit()
{
    next_pack "commit" >/dev/null
}

mark_pack_installed()
{
    local PACK="$1"
    echo "INSTALLED=1">"${PACK}/installed.conf"
}

mark_pack_committed()
{
    local PACK="$1"
    echo "COMMITTED=1">"${PACK}/committed.conf"
}
