#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions

do_umount "${OPTICAL_MOUNT}"

get_and_increment_bad_count()
{
    if [ ! -e "${BAD_MOUNT_CONF}" ] ; then
        BAD_COUNT=1
    else
        . "${BAD_MOUNT_CONF}"
        BAD_COUNT=$((BAD_COUNT + 1))
    fi
    echo "BAD_COUNT=${BAD_COUNT}" >"${BAD_MOUNT_CONF}"
    echo "${BAD_COUNT}"
}

if interactive ; then
    BAD_COUNT="$(get_and_increment_bad_count)"
    if [ "${BAD_COUNT}" -lt "${BAD_THRESHOLD}" ] ; then
        echo "Interactive attempt ${BAD_COUNT}: offering user another chance to configure install.">&2
        exit ${Retry}
    fi
fi
exit ${Abort}
