#!/bin/ash
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
not_previous || exit ${Previous}

# check_gfx:
# Returns true if GPU recognised as Intel:

check_gfx()
{
    for i in /sys/bus/pci/devices/*; do
        if [ -d $i ]; then
            if grep -q '3....$' $i/class; then
                vendor=$(cat $i/vendor)
                case $vendor in
                    "0x8086"|"0x8087") return 0;;
                esac
            fi
        fi
    done

    echo "Warning: no Intel GPU was found, graphics performance will be degraded.">&2
    return 1
}

GPU_OK=0
check_gfx || GPU_OK=1

interactive || exit ${Continue}

if [ ${GPU_OK} -ne 0 ] ; then
    dialog --colors --yes-label "Continue" --no-label "Abort" --yesno \
"      \ZbWarning: no Intel GPU was found\ZB

   Graphics performance will be degraded" 8 48
    OPT=$?
    [ ${OPT} -eq 1 ] && exit ${Abort}
    [ ${OPT} -eq 255 ] && exit ${Previous}
    echo "Ignoring unrecognised graphics device.">&2
fi

exit ${Continue}
