#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions

# TODO: These next two lines lock down the source to optical.
#       Remove them when other sources are supported.
not_previous || exit ${Previous}
exit ${Optical}


if [ -e "${NEXT_PACK_CONF}" ] ; then
    . "${NEXT_PACK_CONF}"
    if [ -z "${SOURCE}" ] || [ -z "${SOURCE_TYPE}" ] ; then
        echo "Error parsing next Supplemental Pack config file">&2
        exit "${Abort}"
    fi
    not_previous || exit ${Previous}
    [ "${SOURCE_TYPE}" != "url" ]       || exit "${Network}"
    [ "${SOURCE_TYPE}" != "nfs" ]       || exit "${Network}"
    [ "${SOURCE_TYPE}" != "local" ]     || exit "${Optical}"
    [ "${SOURCE_TYPE}" != "bootmedia" ] || exit "${BootMedia}"
    # TODO: XC-2911 - handle hard disk installation
fi

if bootfs_includes_extras ; then
    # TODO: it would be an improvement to avoid offering the boot media option
    # if we have already installed all of the packs present in the boot media.
    dialog --extra-button --ok-label "Boot media" --extra-label "CD-ROM" --cancel-label Network --yesno "\n    Install the Supplemental Pack from\n       Boot media, CD-ROM or Network?" 8 50

    OPT=$?
    [ "${OPT}" != "0" ]   || exit ${BootMedia}
    [ "${OPT}" != "3" ]   || exit ${Optical}
    [ "${OPT}" != "1" ]   || exit ${Network}
    [ "${OPT}" != "255" ] || exit ${Previous}

else

    dialog --yes-label "CD-ROM" --no-label Network --yesno "\n  Install the Supplemental Pack\n     from CD-ROM or Network?" 8 40

    OPT=$?
    [ "${OPT}" != "0" ]   || exit ${Optical}
    [ "${OPT}" != "1" ]   || exit ${Network}
    [ "${OPT}" != "255" ] || exit ${Previous}
fi
exit ${Abort}
