#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${SCRIPT_DIR}/Functions/install-main

not_previous || exit ${Previous}

if interactive ; then
    dialog --infobox "\n\nExtracting control package..." 7 35
fi

rm -rf "${INSTALL_ROOT_PART2}"
mkdir -p "${INSTALL_ROOT_PART2}"

extract_xc_control_package "${INSTALL_SOURCE_DIR}/${PACKAGES_DOT_MAIN}" \
                           "${INSTALL_ROOT_PART2}" || exit ${Abort}

exit ${Continue}
