#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# Previous-barrier:
#
# This script disallows the interactive user to step backwards
# past this point.

. ${SCRIPT_DIR}/functions

! not_previous || exit ${Continue}

while [ 1 ] ; do
    dialog --defaultno --yes-label Abort --no-label Install --yesno "
    Do you wish to abort the installation?" 7 50
    OPT=$?
    [ "$OPT" != "0" ]   || exit ${Abort}
    [ "$OPT" != "1" ]   || exit ${Continue}
done
exit ${Abort}
