#!/bin/sh

. ${SCRIPT_DIR}/functions
. /usr/lib/openxt/key-functions

if ! keystore_ready; then
    setup_keystore || exit ${Abort}
fi

if answerfile_specifies "recovery-password" "${FULL_ANSWERFILE}" ; then
    read_xml_tag "${FULL_ANSWERFILE}" "recovery-password" | \
        store_recovery_key
    sanitize_xml_tag "${FULL_ANSWERFILE}" "recovery-password"
    if ! have_recovery_key ; then
        echo "ERROR: Empty Recovery password provided!"
        exit ${Abort}
    fi
fi

if answerfile_specifies "tpm-owner-password" "${FULL_ANSWERFILE}" ; then
    read_xml_tag "${FULL_ANSWERFILE}" "tpm-owner-password" | \
        store_own_key
    sanitize_xml_tag "${FULL_ANSWERFILE}" "tpm-owner-password"
    if ! have_own_key ; then
        echo "ERROR: Empty TPM Owner password provided!"
        exit ${Abort}
    fi
fi

exit ${Continue}
