#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
# ^^^ defines ${INSTALL_STATUS_CONF}

echo "INSTALL='Failure'" >${INSTALL_STATUS_CONF}

if interactive ; then
    dialog --ok-label Continue --msgbox "\n Installation did not succeed." 7 35
else
    kill_welcome_screen
    dialog --infobox "\nInstallation did not succeed.\n\nRebooting..." 7 35
fi
exit ${Continue}
