#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${SCRIPT_DIR}/Functions/optical-media

# This script selects and records the optical device 
# containing the installation package repository.

#------------------------------------------------------------
rm -f "${OPTICAL_CONF}"

DO_VERIFY="ask_or_yes"

if [ -e "${NEXT_PACK_CONF}" ] ; then

    . "${NEXT_PACK_CONF}"

    if [ -z "${SOURCE}" ] ; then
        # warning, not fatal:
        echo "Answerfile <supplemental-pack type=local> did not specify device so will scan.">&2
        locate_cdrom "${PACKAGES_DOT_EXTRA}"
        RET=$?
        [ ${RET} = 0 ] || exit ${RET}
    else
        OPTICAL_DEVICE="${SOURCE}"
    fi

    # false/no: don't ask, don't verify
    if [ "x${SOURCE_VERIFY}" = "xno" ] || [ "x${SOURCE_VERIFY}" = "xfalse" ] ; then
        DO_VERIFY="no"

    # true/yes: don't ask, always verify
    elif [ "x${SOURCE_VERIFY}" = "xyes" ] || [ "x${SOURCE_VERIFY}" = "xtrue" ] ; then
        DO_VERIFY="yes"
    fi
else
    locate_cdrom "${PACKAGES_DOT_EXTRA}"
    RET=$?
    [ ${RET} = 0 ] || exit ${RET}
fi

echo "OPTICAL_DEVICE=${OPTICAL_DEVICE}">"${OPTICAL_CONF}"
echo "OPTICAL_VERIFY=${DO_VERIFY}">>"${OPTICAL_CONF}"

not_previous || exit ${Previous}
exit ${Continue}
