#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions

. ${DISK_CONF}
# ^^^ defines ${TARGET_DISK}

# Answerfile tags:
#
# <install-gpt>true</install-gpt>
# <install-gpt>auto</install-gpt>
# <install-gpt>false</install-gpt>
# <install-gpt><install-gpt>

mbr_in_whitelist()
{
    local MBR_CHECKSUM=$(dd "if=/dev/${TARGET_DISK}" bs=440 count=1 | \
                         sha256sum | \
                         sed 's/ .*//')

    echo "MBR checksum: ${MBR_CHECKSUM}" >&2

    grep -q "^${MBR_CHECKSUM} " "${MBR_WHITELIST}"
}

not_previous || exit ${Previous}

if answerfile_specifies "install-gpt" ; then
    INSTALL_GPT=$(read_xml_tag "${ANSWERFILE}" "install-gpt")

    case "${INSTALL_GPT}" in
        true|false|auto)
            ;;

        "")
            INSTALL_GPT="auto"
            ;;

        *)
            echo "ERROR: Answerfile specifies unknown value '${INSTALL_GPT}'" \
                 "for <install-gpt> tag." >&2
            exit ${Abort}
    esac
else
    INSTALL_GPT="auto"
fi

if [ "${INSTALL_GPT}" = "auto" ] ; then
    if mbr_in_whitelist ; then
        INSTALL_GPT="false"
    else
        INSTALL_GPT="true"
    fi
fi

echo "INSTALL_GPT='${INSTALL_GPT}'" > ${GPT_CONF}

exit ${Continue}
