#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions

rm -f ${SSH_CONF}

if answerfile_specifies "enable-ssh" ; then
    not_previous || exit ${Previous}
    SSH_ENABLED=$(read_xml_tag "${ANSWERFILE}" "enable-ssh")

elif ! interactive ; then
    SSH_ENABLED=false

else
    dialog --yes-label "Yes" --no-label "No" --defaultno --yesno "\nDo you wish to enable external SSH access to this computer?" 8 50

    OPT=$?
    [ "$OPT" != "255" ] || exit ${Previous}
    if [ "${OPT}" = 0 ] ; then
        SSH_ENABLED=true
    else
        SSH_ENABLED=false
    fi
fi

echo "SSH_ENABLED='${SSH_ENABLED}'" >${SSH_CONF}

exit ${Continue}
