#!/bin/ash
#
# Copyright (c) 2011 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions

if [ -z "${PACKAGES_DIR}" ] ; then
    echo "ERROR: PACKAGES_DIR not set" >&2
    exit ${Abort}
fi

not_previous || exit ${Previous}

REPOSITORY_FILE="${PACKAGES_DIR}/${REPOSITORY_FILENAME}"

REPOSITORY_VERSION="$(sed -ne 's/^version://p' ${REPOSITORY_FILE})"
REPOSITORY_RELEASE="$(sed -ne 's/^release://p' ${REPOSITORY_FILE})"
UPGRADEABLE_RELEASES="$(sed -ne 's/^upgrade-from://p' ${REPOSITORY_FILE})"

    cat <<EOF >&2
Repository version: ${REPOSITORY_VERSION}
Repository release: ${REPOSITORY_RELEASE}
Upgradeable releases: ${UPGRADEABLE_RELEASES}
EOF

    cat <<EOF > ${REPOSITORY_CONF}
REPOSITORY_VERSION='${REPOSITORY_VERSION}'
REPOSITORY_RELEASE='${REPOSITORY_RELEASE}'
UPGRADEABLE_RELEASES='${UPGRADEABLE_RELEASES}'
EOF

exit ${Continue}
