#!/bin/bash
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${DISK_CONF}
. ${PARTITION_CONF}
. ${SCRIPT_DIR}/Functions/install-main

create_efi_system_partition()
{
    local PARTITION="${XC_PARTITION}"
    local DISK=$(get_partition_disk "${PARTITION}")
    local DISK_DEV="/dev/${DISK}"

    local EFI_SYSTEM_PARTITION_GUID="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
    local ESP=$(sfdisk -d ${DISK_DEV} | grep "type=${EFI_SYSTEM_PARTITION_GUID}" | awk '{ print $1 }')
    local ESP_PARTNUM="1"
    local ESP_SIZE="+100M"  # 1 MiB
    local ESP_TYPE="EF00" # EFI System Partition Typecode

    if [ "${ESP}" != "" ]; then
        echo "ESP already exists, continue." >&2
        return 0
    fi

    echo "No ESP detected, attempting to create a ESP." >&2

    # Create the ESP
    if ! do_cmd sgdisk -g -n ${ESP_PARTNUM}::${ESP_SIZE} -t ${ESP_PARTNUM}:${ESP_TYPE} "${DISK_DEV}" >&2 ; then
        echo "ERROR: Could not create EFI System Partition." >&2
        return 1
    fi

    ESP=$(sfdisk -d ${DISK_DEV} | grep "type=${EFI_SYSTEM_PARTITION_GUID}" | awk '{ print $1 }')

    if ! do_cmd mkfs.vfat -F 32 "${ESP}" >&2 ; then
        echo "ERROR: Could not format ESP at '${ESP}' as FAT32" >&2
        return 1
    fi

    return 0
}

create_efi_system_partition || exit ${Abort}

exit ${Continue}
