#!/bin/ash
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${DISK_CONF}
. ${PARTITION_CONF}
. ${SCRIPT_DIR}/Functions/install-main

# GRUB Stage 1.5 lives in the BIOS Boot Partition
# GRUB2 will automatically find this partition when grub is installed
create_bios_boot_partition()
{
    local PARTITION="${XC_PARTITION}"
    local DISK=$(get_partition_disk "${PARTITION}")
    local DISK_DEV="/dev/${DISK}"

    local BBP_PARTNUM="1"
    local BBP_SIZE="+1M"  # 1 MiB
    local BBP_TYPE="EF02" # BIOS Boot Partition Typecode

	if do_cmd sgdisk -p "${DISK_DEV}" | grep -i ${BBP_TYPE} >&2 ; then
		echo "BBP already exists, continue." >&2
		return 0
	fi

	echo "No BBP detected, attempting to create a BBP." >&2
    # Create the BBP
    if ! do_cmd sgdisk -g -n ${BBP_PARTNUM}::${BBP_SIZE} -t ${BBP_PARTNUM}:${BBP_TYPE} "${DISK_DEV}" >&2 ; then
        echo "ERROR: Could not create BIOS Boot Partition." >&2
        return 1
    fi

    return 0
}

create_bios_boot_partition || exit ${Abort}

exit ${Continue}
