#!/bin/ash
#
# Copyright (c) 2013 Citrix Systems, Inc.
# Copyright (c) 2016 Daniel P. Smith, Apertus Solutions, LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${SCRIPT_DIR}/Functions/install-main

. ${INSTALL_MODE_CONF}

[ ! -r ${EXISTING_CONF} ] || . ${EXISTING_CONF}

. ${REPOSITORY_CONF}

TPM_FUNC=/usr/lib/tpm-scripts/tpm-functions
MLE_FUNC=/usr/lib/openxt/ml-functions
[ ! -r ${TPM_FUNC} ] || . ${TPM_FUNC}
[ ! -r ${MLE_FUNC} ] || . ${MLE_FUNC}
[ ! -r ${MEASURED_LAUNCH_CONF} ] || . ${MEASURED_LAUNCH_CONF}

do_umount_all

if interactive ; then
    dialog --infobox "\n\nSealing upgrade..." 7 35
fi

seal_system || {
    dialog --ok-label Continue --msgbox "Error: seal_system failed." 0 0
    exit ${Abort}
}

exit ${Continue}

