#!/bin/ash
#
# Copyright (c) 2013 Citrix Systems, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

. ${SCRIPT_DIR}/functions
. ${MEASURED_LAUNCH_CONF}

not_previous || exit ${Previous}

if [ "${MEASURE_LAUNCH}" = "true" ]; then
    if ! interactive; then
        echo "ERROR: answerfile specifies that ${PRODUCT_BRAND} Measured" \
             "Launch should be configured but ${PRODUCT_BRAND} was unable to" \
             "establish a Measured Launch Environment.  Check your BIOS" \
             "settings and enable TXT.  Also try shutting your system down" \
             "completely to clear the TXT error registers." >&2
        exit ${Abort}
    else
        dialog --colors \
            --yes-label "Reboot" \
            --no-label "Continue" \
            --yesno \
"\n
TXT is required for \Zb${PRODUCT_BRAND} Measured Launch.\ZB
\n\n
To enable TXT:\n\n
 1. Reboot and enter the BIOS configuration.\n
 2. Ensure that both TXT and TPM are enabled.\n
 3. \ZbPower OFF the machine completely.\ZB\n
\n
You may \ZbReboot\ZB the system now to activate
TXT, or \ZbContinue\ZB the installation with
${PRODUCT_BRAND} Measured Launch disabled." 17 54
        case $? in
            1) exit ${Continue} ;;
            255) exit ${Previous} ;;
            *) exit ${Abort} ;;
        esac
    fi
else
    # elected not to configure measured launch anyway
    # error is irrelevant
    exit ${Continue}
fi
